caption_dir: /scratch/yk3281/dataset/clotho
audio_root_dir: /scratch/yk3281/dataset/clotho
train_split: development
validation_split: validation
inference_split: evaluation

batch_size: 8
num_workers: 8
epochs: 20
early_stopping_patience: 5
lr: 0.0001
weight_decay: 0.01

audio_dim: 768
max_length: 128
preview_num_samples: 5
audio_sample_rate: 44100
do_sample: false

lora_r: 16
lora_alpha: 32
lora_dropout: 0.05

save_dir: outputs/r16_a32_d-5
best_checkpoint_path: outputs/r16_a32_d-5/r16_a32_d-5_best.pt
output_csv_path: r16_a32_d-5_results.csv
prompt_text: "Describe this audio:"

# wandb
use_wandb: true
project: "audio-captioning"
entity: "yujin-kimmm-new-york-university"
name: "r16_a32_d-5"
wandb_dir: wandblog/r16_a32_d-5
